default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:123456@localhost/rails_with_react" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_TEST_URL") { "postgres://postgres:123456@localhost/rails_with_react_test" } %>

development:
  <<: *default

production:
  <<: *default
